RHDIP-2060: Update name reference
redhat-developer/red-hat-developers-documentation-rhdh pull request #196
Opened 2024-04-24 15:58 UTC by abrennan89

**Versions:**
1.1+

**Jira link:**
https://issues.redhat.com/browse/RHIDP-2060

**Preview link:**
TBA

**Reviews:**
- [ ] SME:
- [ ] QE:
- [ ] Peer review:

2024-04-25 07:23 UTC, zdrapela requested changes
The `{ocp-brand-name}` is used only in prerequisites, as far as I know. Other parts of the documentation use generally the `{ocp-short}`.

2024-04-25 15:10 UTC, nickboldt commented on installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
> +* You have access to the {ocp-brand-name} image registry of your cluster. For more information about exposing the image registry, see the {ocp-brand-name} documentation about https://docs.openshift.c
```suggestion
* You have access to the {ocp-short} image registry of your cluster. For more information about exposing the image registry, see the {ocp-short} documentation about https://docs.openshift.com/container-platform/{ocp-version}/registry/securing-exposing-registry.html[Exposing the registry].
```

2024-04-25 21:16 UTC, linfraze approved these changes
Peer review complete - lgtm

2024-04-25 21:16 UTC, linfraze commented on installation/proc-install-rhdh-airgapped-environment-ocp-helm.adoc
> +* You have access to the {ocp-brand-name} image registry of your cluster. For more information about exposing the image registry, see the {ocp-brand-name} documentation about https://docs.openshift.c
Per minimalism principle 1, we typically use the _For more information about [topic], see [link]_ format (so the _in OpenShift documentation_ was never even necessary) - just an fyi; definitely won't block the merge

2024-04-26 05:04 UTC, zdrapela approved these changes

2024-04-26 14:21 UTC, merged

2024-04-26 14:21 UTC, abrennan89 commented
/cherrypick 1.1.x