RHIDP-2596: update OIDC auth provider configurations
redhat-developer/red-hat-developers-documentation-rhdh pull request #265
Opened 2024-06-07 13:59 UTC by Zaperex

### Description
Update the OIDC Auth Provider documentation to reflect the changes made in https://github.com/janus-idp/backstage-showcase/pull/1309

2024-06-10 08:22 UTC, hmanwani-rh requested changes
@Zaperex Thank you for creating the PR and incorporating these changes into the docs. I've added a couple of minor suggestions. Could you please review them and let me know if you have any questions?

2024-06-10 08:22 UTC, hmanwani-rh commented on modules/getting-started/con-oidc-overview.adoc
> +        ## Auth provider will try each sign-in resolver until it succeeds. Comment out the resolvers you do not want
```suggestion
        ## The auth provider will try each sign-in resolver until it succeeds. Comment out the resolvers you do not want to use.
```

2024-06-10 08:22 UTC, hmanwani-rh commented on modules/getting-started/con-oidc-overview.adoc
> +If no resolvers are provided, the OIDC authentication provider will default to no resolvers and will not function.
```suggestion
If no resolvers are provided, the OIDC authentication provider defaults to having no resolvers and therefore does not function.
```

2024-06-12 14:07 UTC, zdrapela approved these changes
Looking good to me! 👍️

2024-06-13 01:29 UTC, hmanwani-rh approved these changes

2024-06-13 01:29 UTC, merged

2024-06-13 01:29 UTC, hmanwani-rh commented
/cherrypick 1.2.x