RHIDP-3111 Replace references to deprecated backend.auth.keys config
redhat-developer/red-hat-developers-documentation-rhdh pull request #614
Opened 2024-10-10 14:02 UTC by themr0c

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.3.1

**Issue:** https://issues.redhat.com/browse/RHIDP-3111

**Link to docs preview:**

**Reviews:**
- [ ] SME: @ mention assignee
- [ ] QE: @ mention assignee
- [ ] Docs review: @ mention assignee
- [ ] Additional review: @mention assignee (by writer)

**Additional information:**

2024-10-10 15:35 UTC, 04kash commented on modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc
>            - secret: "${BACKEND_SECRET}" # <2>
```suggestion
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
```

2024-10-10 15:40 UTC, 04kash requested changes
Made a few changes. @rm3l could you take a look and see if this needs to be updated anywhere else?

2024-10-10 15:40 UTC, 04kash commented on modules/installation/proc-deploy-rhdh-instance-eks.adoc
>            - secret: "${BACKEND_SECRET}"
```suggestion
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
```

2024-10-10 15:40 UTC, 04kash commented on modules/installation/proc-rhdh-deploy-aks-operator.adoc
>            - secret: "${BACKEND_SECRET}"
```suggestion
        externalAccess:
            - type: legacy
              options:
                subject: legacy-default-config
                secret: "${BACKEND_SECRET}"
```

2024-10-10 16:11 UTC, rm3l commented
/cc

2024-10-10 19:41 UTC, rm3l requested changes
> Made a few changes. @rm3l could you take a look and see if this needs to be updated anywhere else?

+1 to the review comments already written. I didn't see other files that would need to be updated other than the ones here.

2024-10-11 08:14 UTC, albarbaro reviewed
Agree on the changes already requested

2024-10-11 09:38 UTC, themr0c commented on modules/installation/proc-add-custom-app-config-file-ocp-operator.adoc
> +                secret: "${BACKEND_SECRET}"
```suggestion
                secret: "${BACKEND_SECRET}" # <2>
```

2024-10-11 09:39 UTC, themr0c commented
/cherry-pick release-1.3

2024-10-11 10:55 UTC, hmanwani-rh approved these changes

2024-10-11 10:56 UTC, merged

2024-10-11 10:56 UTC, hmanwani-rh commented
/cherry-pick release-1.3