RHIDP-1764: Document minimum resource requirements for Operator
redhat-developer/red-hat-developers-documentation-rhdh pull request #626
Opened 2024-10-15 13:51 UTC by hmanwani-rh

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):**
1.3

**Issue:**
[RHIDP-1764](https://issues.redhat.com/browse/RHIDP-1764)

**Link to docs preview:**
Find the link within this PR

**Reviews:**
- [x] SME: @rm3l 
- [x] QE: @zdrapela 
- [x] Docs review: @themr0c 

**Additional information:**

2024-10-15 14:01 UTC, hmanwani-rh commented
@rm3l, @themr0c Please review this PR and share your approval

2024-10-16 09:18 UTC, rm3l requested changes

2024-10-16 09:18 UTC, rm3l commented on modules/getting-started/ref-rhdh-sizing.adoc
> +|256 Mi
```suggestion
|1500 Mi
```

Based on what we have in https://github.com/redhat-developer/rhdh-operator/blob/main/.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml#L283, the memory limit of the controller container has been increased to 1 Gi. Taking into account the kube-rbac-proxy container limit set to [128 Mi](https://github.com/redhat-developer/rhdh-operator/blob/main/.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml#L239), I think we should update this.

2024-10-16 09:18 UTC, rm3l commented on modules/getting-started/ref-rhdh-sizing.adoc
> +|NA
```suggestion
|1
```

I would say exactly 1 replica, as the operator is cluster-wide atm, and we want to have a single instance of it running.

2024-10-16 09:18 UTC, rm3l commented on modules/getting-started/ref-rhdh-sizing.adoc
> +|NA
```suggestion
|50 Mi
```

The operator needs some ephemeral storage - see https://github.com/redhat-developer/rhdh-operator/blob/main/.rhdh/bundle/manifests/rhdh-operator.clusterserviceversion.yaml#L282

2024-10-16 09:58 UTC, rm3l approved these changes

2024-10-17 13:43 UTC, zdrapela approved these changes

2024-10-17 14:21 UTC, hmanwani-rh commented on modules/getting-started/ref-rhdh-sizing.adoc
> +|1
Done

2024-10-17 14:34 UTC, themr0c approved these changes

2024-10-17 14:36 UTC, merged

2024-10-17 14:36 UTC, themr0c commented
/cherry-pick release-1.3