RHIDP-3334: apiversion and kind update
redhat-developer/red-hat-developers-documentation-rhdh pull request #695
Opened 2024-11-12 09:02 UTC by pabel-rh

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.2.x, 1.3.x, main

**Issue:** RHIDP-3334

**Link to docs preview:**

**Reviews:**
- [ ] SME: @rm3l 
- [ ] QE: @ mention assignee
- [ ] Docs review: @jmagak 
- [ ] Additional review: @mention assignee (by writer)

**Additional information:**

2024-11-12 09:13 UTC, rm3l requested changes

2024-11-12 09:13 UTC, rm3l commented on assemblies/assembly-add-custom-app-file-openshift.adoc
> +kind: Backstage
I don't think this is the YAML that needs to be changed. This is a valid ConfigMap manifest and seems to be common to the procedures for both Helm and Operator. The error was specific to the Operator.

![image](https://github.com/user-attachments/assets/165d12bd-ae91-4df0-9c0a-e0a559a13329)

2024-11-12 09:56 UTC, rm3l approved these changes
Thanks @pabel-rh !

2024-11-12 10:14 UTC, jmagak reviewed
LGTM

2024-11-14 19:03 UTC, josephca commented
/lgtm

2024-11-18 15:41 UTC, merged

2024-11-18 15:42 UTC, Gerry-Forde commented
/cherrypick release-1.3

2024-11-18 15:51 UTC, Gerry-Forde commented
/cherrypick 1.2.x