chore: update migrated plugins locations
redhat-developer/red-hat-developers-documentation-rhdh pull request #825
Opened 2024-12-22 16:49 UTC by 04kash

Continuation of https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/pull/824. This PR updates references to plugins to use their new locations

**IMPORTANT: Do Not Merge - To be merged by Docs Team Only**

**Version(s):** 1.4, 1.5

Add the relevant labels to the Pull Request.
**Issue:**

2024-12-22 16:53 UTC, 04kash commented on modules/using-service-now/proc-enable-servicenow-custom-actions-plugin.adoc
> +      - package: /dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic
```suggestion
      - package: ./dynamic-plugins/dist/backstage-community-plugin-scaffolder-backend-module-servicenow-dynamic
```

2024-12-22 16:57 UTC, 04kash commented
cc: @nickboldt @BethGriggs

2024-12-22 16:59 UTC, 04kash commented on artifacts/rhdh-plugins-reference/keycloak/keycloak-plugin-readme.adoc
> +      - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic`
```suggestion
      - package: ./dynamic-plugins/dist/backstage-community-plugin-catalog-backend-module-keycloak-dynamic
```

2024-12-23 10:48 UTC, dzemanov requested changes
Great work. Just 2 more:
- https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/blob/main/artifacts/rhdh-plugins-reference/quay/quay-install-dynamic-plugin.adoc:
   - package: ./dynamic-plugins/dist/janus-idp-backstage-plugin-quay
- https://github.com/redhat-developer/red-hat-developers-documentation-rhdh/blob/main/artifacts/rhdh-plugins-reference/topology/topology-plugin-readme.adoc
   - You can use the https://raw.githubusercontent.com/janus-idp/backstage-plugins/main/plugins/topology/manifests/clusterrole.yaml[prepared manifest for a rea
d-only `ClusterRole`], which provides access for both Kubernetes and Topology plugin.

2024-12-23 15:07 UTC, dzemanov approved these changes

2024-12-24 14:49 UTC, hmanwani-rh approved these changes

2024-12-24 15:22 UTC, nickboldt commented
/cherry-pick release-1.4

2025-01-02 07:16 UTC, merged

2025-01-02 07:18 UTC, themr0c commented
@04kash Automated cherry-pick failed. Therefore, can you raise a pull request referencing this pull request with the changes for the release-1.4 branch?