docs: Adding OAuth2 proxy as an authentication provider
redhat-developer/red-hat-developers-documentation-rhdh pull request #83
Opened 2024-03-14 11:26 UTC by themr0c

docs: Adding OAuth2 proxy as an authentication provider

fixes https://issues.redhat.com/browse/RHIDP-1474

2024-03-22 10:26 UTC, themr0c commented
Hi @kadel can you have a look at this? The current content is inspired from upstream. I expect the behavior to be different. Can you give me some hints?

2024-03-27 08:46 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +
We should also document how to deploy oauth2-proxy as a sidecar container for RHDH

2024-04-15 11:52 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +
There is a blog post that documents how to do that: https://janus-idp.io/blog/2023/01/17/enabling-keycloak-authentication-in-backstage#deploying-backstage-using-the-backstage-helm-chart


TL;DR for helm chart it requries adding extra container to helm config

```yaml
  extraContainers:
    - name: oauth2-proxy
      env:
        - name: OAUTH2_PROXY_CLIENT_ID
          value: '{{ required "Keycloak Client Secret is Required" .Values.keycloak.clientId }}'
        - name: OAUTH2_PROXY_CLIENT_SECRET
          value: '{{ required "Keycloak Client Secret is Required" .Values.keycloak.clientSecret }}'
        - name: OAUTH2_PROXY_COOKIE_SECRET
          value: '{{ default (randAlpha 32 | lower | b64enc) .Values.keycloak.cookieSecret }}'
        - name: OAUTH2_PROXY_OIDC_ISSUER_URL
          value: '{{ required "Keycloak Issuer URL is Required" .Values.keycloak.issuerUrl }}'
        - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
          value: 'true'
      ports:
        - name: oauth2-proxy
          containerPort: 4180
          protocol: TCP
      imagePullPolicy: IfNotPresent
      image: 'quay.io/oauth2-proxy/oauth2-proxy:latest'
      args:
        - '--provider=oidc'
        - '--email-domain=*'
        - '--upstream=http://localhost:7007'
        - '--http-address=0.0.0.0:4180'
        - '--skip-provider-button'
```

When installing via Operator this is currently not possible to do due to https://issues.redhat.com/browse/RHIDP-1760

2024-06-10 11:25 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +  environment: development
```suggestion
  environment: production
```

2024-06-10 11:27 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +Add the `oauth2Proxy` provider configuration to your `app-config.yaml` under the root `auth` configuration:
We should align working with other auth providers. For example in Azure auth provider ther is 

>Edit your custom {product-short} config map, such as `app-config-rhdh`.

>In the `app-config-rhdh.yaml` content, add the `microsoft` provider configuration >under the root `auth` configuration, and enable the `microsoft` provider for sign-in:

2024-06-10 11:28 UTC, kadel requested changes

2024-06-10 11:28 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +.`packages/backend/src/plugins/auth.ts`
In RHDH container it is not possible to edit files like this, there needs to be another way to configure this

2024-06-10 11:28 UTC, kadel commented on modules/auth/proc-adding-oauth2-proxy-as-an-authentication-provider.adoc
> +The following example for OAuth2-proxy shows the additions needed to `packages/app/src/App.tsx`:
In RHDH container it is not possible to edit files like this, there needs to be another way to configure this

2024-06-28 13:31 UTC, briandooley commented
Triage: Closing as we do not currently support this.

2024-06-28 13:31 UTC, closed without merging